apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  # replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: us.gcr.io/k8s-artifacts-prod/hpa-example
        name: guestbook-ui
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 20m
            memory: 10Mi